name: Feature Request
description: Suggest an idea or enhancement
title: '[Feature] '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please check existing issues first to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point does it address?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: It would be great if erzencode could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: How would this feature be used? Provide specific examples.
      placeholder: |-
        1. When I'm working on X, I would use this to...
        2. This would help me accomplish Y by...

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area of the project does this affect?
      options:
        - CLI / Terminal UI
        - Web UI
        - AI Agent / Tools
        - Provider Support
        - Configuration
        - Documentation
        - Other
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Willing to contribute?
      options:
        - label: Yes, I'd like to work on this feature
          required: false
        - label: Yes, but I need guidance
          required: false
        - label: No, I'm unable to contribute at this time
          required: false
